# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
