# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170901_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Advert Sales Executives', 'Advert Sales Executives'), ('Content Writer', 'Content Writer'), ('Social Media Executives', 'Social Media Executives')], default='Content Writer', max_length=50, null=True),
        ),
    ]
