# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170930_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
