# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=70)),
                ('advert_banner', models.ImageField(upload_to=b'')),
                ('advert_desc', models.TextField()),
                ('duration', models.IntegerField()),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=50)),
            ],
        ),
    ]
