# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20170829_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='payt_status',
            field=models.BooleanField(default=False),
        ),
    ]
