# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20170904_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
