# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20170904_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='Owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
