# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_auto_20170904_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='advert_banner',
            field=models.ImageField(upload_to='media'),
        ),
    ]
