# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_auto_20170905_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=50)),
                ('cost', models.IntegerField()),
                ('page', models.CharField(choices=[('home', 'home'), ('detail', 'detail')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='advert',
            name='frequency',
        ),
        migrations.AddField(
            model_name='advert',
            name='advert_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.advertPlan'),
        ),
    ]
