# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20170905_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
