# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0014_auto_20170916_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duration',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='duration',
        ),
        migrations.AddField(
            model_name='advertplan',
            name='price',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='advertplan',
            name='name',
            field=models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('Quaterly', 'Quaterly'), ('Anually', 'Anually')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
