# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0015_auto_20170916_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertplan',
            name='frequency',
            field=models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('Quaterly', 'Quaterly'), ('Anually', 'Anually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertplan',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertplan',
            name='price',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
