# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0017_auto_20170916_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='duration',
            field=models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('Quaterly', 'Quaterly'), ('Anually', 'Anually')], max_length=50, null=True),
        ),
    ]
