# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0018_auto_20170918_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
