# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0019_auto_20171002_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfrom', models.DateField()),
                ('rto', models.DateField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
