# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(b'News', b'News'), (b'Trend', b'Trend')], default=b'News', max_length=100),
        ),
    ]
