# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(b'News', b'News'), (b'Trend', b'Trend'), (b'Weird Houses', b'Weird Houses'), (b'My Story', b'My Story'), (b'Business', b'Business'), (b'Entertainment', b'Entertainment'), (b'Around the Web', b'Around the Web'), (b'Advertise with Us', b'Advertise with Us')], default=b'News', max_length=100),
        ),
    ]
