# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170911_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b'postpics'),
        ),
    ]
