# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170919_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='WriterProfile',
        ),
    ]
