# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contactmessage_subscribeemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeemail',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscribeemail',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
