# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170929_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pageview',
            field=models.IntegerField(default=0),
        ),
    ]
