# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171005_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blur_thumb',
        ),
    ]
