# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_blur_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_image_tools.Image'),
        ),
    ]
