# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171005_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Submitted', 'Submitted')], default='Draft', max_length=100),
        ),
    ]
